{% set name = "environment-modules" %}
{% set version = "5.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cea-hpc/modules/releases/download/v{{ version }}/modules-{{ version }}.tar.bz2
  sha256: 28354dd1ab2ff25e9fb9ce759c77eeefec21f22a112d579fbf3cc802174ec944
  patches:
    - no-pager-check.diff

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
      - {{ compiler('c') }}
      - make
  host:
      - tk
      - zlib
  run:
      - {{ pin_compatible('tk') }}
      - {{ pin_compatible('zlib') }}

test:
  commands:
    - module --version 2>&1 | grep "Modules Release {{ version }}"

about:
  home: http://modules.sourceforge.net/
  license_family: GPL
  license: GPL-2.0-only
  license_file: COPYING.GPLv2
  summary: 'The Environment Modules package is a tool that simplify shell
initialization and lets users easily modify their environment during the
session with modulefiles.'
  description: |
     Typically users initialize their environment when they log in by setting
     environment information for every application they will reference during the
     session. The Environment Modules package is a tool that simplify shell
     initialization and lets users easily modify their environment during the
     session with modulefiles.

     Each modulefile contains the information needed to configure the shell for an
     application. Once the Modules package is initialized, the environment can be
     modified on a per-module basis using the module command which interprets
     modulefiles. Typically modulefiles instruct the module command to alter or set
     shell environment variables such as PATH, MANPATH, etc. modulefiles may be
     shared by many users on a system and users may have their own collection to
     supplement or replace the shared modulefiles.

     Modules can be loaded and unloaded dynamically and atomically, in an clean
     fashion. All popular shells are supported, including bash, ksh, zsh, sh, csh,
     tcsh, as well as some scripting languages such as perl and python.

     Modules are useful in managing different versions of applications. Modules can
     also be bundled into metamodules that will load an entire suite of different
     applications.
  doc_url: http://modules.sourceforge.net/
  dev_url: https://github.com/cea-hpc/modules

extra:
  recipe-maintainers:
    - jerowe
    - julozi
