{% set name = "environment-modules" %}
{% set version = "4.6.0" %}
{% set sha256 = "b42b14bb696bf1075ade1ecaefe7735dbe411db4c29031a1dae549435eafa946" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://prdownloads.sourceforge.net/modules/modules-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - gcc    # [linux]
    - llvm    # [osx]
    - tk 8.6.*
    - zlib 1.2.*
  run:
    - libgcc    # [linux]
    - tk 8.6.*
    - zlib 1.2.*

test:
  commands:
    - module --version 2>&1 | grep "Modules Release 4.1.4"  # [linux]
    - module --version 2>&1 | grep "Modules Release 4.1.4"  # [osx]

about:
  home: http://modules.sourceforge.net/
  license: GNU
  license_family: GPL
  license_file: COPYING.GPLv2
  summary: The Environment Modules package is a tool that simplify shell initialization and lets users easily modify their environment during the session with modulefiles.
  description: |
    Typically users initialize their environment when they log in by setting
    environment information for every application they will reference during the
    session. The Environment Modules package is a tool that simplify shell
    initialization and lets users easily modify their environment during the
    session with modulefiles.

    Each modulefile contains the information needed to configure the shell for an
    application. Once the Modules package is initialized, the environment can be
    modified on a per-module basis using the module command which interprets
    modulefiles. Typically modulefiles instruct the module command to alter or set
    shell environment variables such as PATH, MANPATH, etc. modulefiles may be
    shared by many users on a system and users may have their own collection to
    supplement or replace the shared modulefiles.

    Modules can be loaded and unloaded dynamically and atomically, in an clean
    fashion. All popular shells are supported, including bash, ksh, zsh, sh, csh,
    tcsh, as well as some scripting languages such as perl and python.

    Modules are useful in managing different versions of applications. Modules can
    also be bundled into metamodules that will load an entire suite of different
    applications.
  doc_url: http://modules.sourceforge.net/
  dev_url: http://modules.sourceforge.net/

extra:
  recipe-maintainers:
    - jerowe
    - julozi
