appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RmZNSCb/XlI/d80wSzj91/CRNVRpuQtG1ZLvQ7Vm7DMi/nkPe1yAAJusgeyUWuE4xNJhO7FOPKttPgsjGuoQLUzqkH+m7hlr0hbtbVhOSOHtUkURzIpcyDPC0D7u/Bna0xUVTiSI8INgNAo4xtx2GKsH6m8yFaovBKZtmPkEfIe0W28rqy2tSm3SS/akYCb3C3SksxlhILf0+q1VIO1/aMdKx3pHPuozcSSiiTpDuikK2KhVWaSte/jEe6+We95KwEcXPilW/uxYHXwUyCPEG8ui7KMe30XjKyTs+TKpnZzDMpjSoz7NSKp16THBKNxhsleJtBKcaN3mj5K0ikHoI50fBwYunfKOXruqbxzr4hV4zn9kNSIOte8UtIc+OPKVIr3WA7+5nxBWT/S5WfWDcsQT8mipm2A4iL1WaX/yZzdpPl2pr/KCEqCvzBTGDJtYv14AFASGbiRC5cd43WPcvgckOEs09XNlhMwYTsNOLq1Yz7UOSmpvCPxRs8HwjkamgzdK+aClz/3FJiKygthIRHaVB/yQhRCqqq3+C7Owy80R7WPH5GQE2HdnegYIJrmvmUo2imK3xGxcy0ORZ7fLzX83+YzOlIsrm+qoR+7bOPzWVbucfiqX/rI9/IRm0YFpQTLE4iSzCW0GYMsGIeM/oOqhWnku/CpTFgO6Aq4+qgY=}
